wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.34.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694505035.578973
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.8.16
      5: 0.15.4
      6: 4.34.0.dev0
      8:
      - 5
