wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690908713.750561
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      3:
      - 23
      4: 3.8.13
      5: 0.15.4
      6: 4.28.1
      8:
      - 5
